---
title: "Joe's website"
author: "Joe Leibrandt"
date: "2/7/2019"
output: 
  html_document:
    theme: spacelab
    toc: true 
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About

I am a Certified Data Science Professional with extensive experience in data reporting and visualization, technical writing, business market research, and information technology consulting. I can assist in the gathering, organizing and analyzing of corporate data for dissemination to internal and external stakeholders.  My personal abilities include attention to detail, active listening, and excellent writing skills.

## Interests

* Data visualization
* Data analysis

## Projects

* Identifying profiles of households who own their real estate with mortgage or loan
* Analyzing Chicago's violent crime rate for potential real estate development
* Patent for craft beer refrigerator
* Health Information Exchange startup 

## Profiles

* [LinkedIn](https://www.linkedin.com/in/josephleibrandt/)
* [GitHub](https://github.com/josephleibrandt)

## Contact

[josephleibrandt@alumni.upenn.edu](mailto:josephleibrandt@alumni.upenn.edu)
